version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis:6379"
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network
